---
- name: Test helm
  hosts: 127.0.0.1
  connection: local
  vars:
    elasticsearch:
      hosts: a
  tasks:
    - include_role:
        name: debug
      vars:
        elasticsearch:
          hello: world
    - include_role:
        name: debug
      vars:
        elasticsearch:
          hosts: c
