---
- name: Deploy Djobi metrics
  hosts: 127.0.0.1
  connection: local
  # remote_user: user
  # become: yes
  # become_method: sudo
  vars:
    helan_product:
      name: djobi-metrics
      dir: djobi_metrics

    ingress_domain_prefix: djobi-metrics

    elk:
      helm_version: 7.8.1
      version: 7.8.1
      flavor: ""

  tasks:
    - name: Build, install elasticsearch
      include_role:
        name: helan
      tags:
      - elasticsearch
      - all
      vars:
        helan_component:
          name: elasticsearch
          fullname: "{{helan_product.name}}-elasticsearch"
          build_dir: "{{build_dir}}/{{helan_product.dir}}/elasticsearch"
          config:
            replicas: 3
            clusterName: "{{ helan_product.name }}"
            nodeGroup: "es"
            hasMasterGroup: false
            storage:
              size: "20Gi"
            resources:
              heap: "1G"
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
            ingress:
              host: "{{ingress_domain_prefix}}-es.{{ingress_domain_suffix}}"
              certif:
                name: "{{helan_product.name}}-elasticsearch-ssl"
          chart:
            name: "elastic/elasticsearch"
            version: "{{ elk.helm_version }}"

    - name: Build, install kibana
      include_role:
        name: helan
      tags:
      - kibana
      - all
      vars:
        helan_component:
          name: kibana
          fullname: "{{helan_product.name}}-kibana"
          build_dir: "{{build_dir}}/{{helan_product.dir}}/kibana"
          config:
            elasticsearch:
              hosts: "{{ helan_product.name }}-es"
            ingress:
              host: "{{ingress_domain_prefix}}.{{ingress_domain_suffix}}"
              certif:
                name: "{{helan_product.name}}-kibana-ssl"
          chart:
            name: "elastic/kibana"
            version: "{{ elk.helm_version }}"


    - name: Build, install APM server
      include_role:
        name: helan
      tags:
      - apm
      - all
      vars:
        helan_component:
          name: apm
          fullname: "{{helan_product.name}}-apm"
          build_dir: "{{build_dir}}/{{helan_product.dir}}/apm"
          config:
            ingress:
              host: "{{ingress_domain_prefix}}-apm.{{ingress_domain_suffix}}"
              certif:
                name: "{{helan_product.name}}-apm-ssl"
            elasticsearch:
              host: "{{ helan_product.name }}-es"
            kibana:
              host: "{{ helan_product.name }}-kibana"
          chart:
            name: "elastic/apm-server"
            version: "{{ elk.helm_version }}"

    - name: Build, install metricbeat (disabled)
      when: false # Disable
      include_role:
        name: helan
      tags:
      - metricbeat
      - never
      vars:
        helan_component:
          name: metricbeat
          fullname: "{{helan_product.name}}-metricbeat"
          build_dir: "{{build_dir}}/{{helan_product.dir}}/metricbeat"
          values_yaml:
            managedServiceAccount: false
            imageTag: "{{ elk.version }}"
            fullnameOverride: "{{helan_product.name}}-metricbeat"
            serviceAccount: "default"
            kube_state_metrics:
              enabled: false
            daemonset:
              enabled: false
              metricbeatConfig: false
            deployment:
              enabled: true
              metricbeatConfig:
                metricbeat.yml: |
                  logging.level: debug
                  setup.dashboards.enabled: true
                  setup.kibana:
                    host: "{{ helan_product.name }}-kibana"
                    protocol: "http"
                    space.id: "metrics"
                  metricbeat.modules:
                  - module: elasticsearch
                    metricsets:
                    - index
                    period: 10s
                    hosts: ["http://conso-es-master:9200"]
                    #username: "user"
                    #password: "secret"
                    xpack.enabled: false
                  - module: kubernetes
                    enabled: false
                    metricsets:
                      - state_node
                      - state_deployment
                      - state_replicaset
                      - state_pod
                      - state_container
                    period: 10s
                    hosts: ["${KUBE_STATE_METRICS_HOSTS}"]
                  output.elasticsearch:
                    hosts: "{{ helan_product.name }}-es:9200"

          chart:
            name: "elastic/metricbeat"
            version: "{{ elk.helm_version }}"

    # https://github.com/helm/charts/tree/master/stable/elasticsearch-exporter
    - name: Build, install elasticsearch exporter
      include_role:
        name: helan
      tags:
      - elasticsearch_exporter
      - all
      vars:
        helan_component:
          name: es-exporter
          fullname: "{{helan_product.name}}-es-exporter"
          build_dir: "{{build_dir}}/{{helan_product.dir}}/es-exporter"
          values_yaml:
            log:
              level: info
            replicaCount: 1
            fullnameOverride: "{{helan_product.name}}-es-exporter"
            es:
              uri: "http://{{ helan_product.name }}-es:9200"
              all: false
              indices: true
              indices_settings: false
              shards: false
              snapshots: false
              cluster_settings: false
            serviceMonitor:
              enabled: true
              interval: 60s
              scrapeTimeout: 20s
          chart:
            name: "stable/elasticsearch-exporter"
            version: "3.6.0"
