---
- name: Create docker registry connection secret
  shell: "kubectl create secret docker-registry  --docker-server={{ registry.url }} --docker-username={{ registry.username }} --docker-password={{ registry.password }} --docker-email={{ registry.email }}"
